#pragma once

#include <cstdint>

// FZX-oriented metadata generated by the fzx transformer plugin.
// Intended to be passed via snatch_font.user_data.
struct snatch_fzx_glyph_info {
    int codepoint{32};
    std::uint8_t kern{0};    // 0..3
    std::uint8_t shift{0};   // 0..15
    std::uint8_t width{1};   // 1..16
    std::uint8_t depth{0};   // 0..192
    std::uint8_t left{0};    // source bitmap bounds
    std::uint8_t right{0};   // source bitmap bounds
    std::uint8_t top{0};     // source bitmap bounds
    std::uint8_t bottom{0};  // source bitmap bounds
    std::uint8_t empty{1};   // 1 if no set pixels in glyph
    std::uint16_t offset_hint{0}; // reserved for exporter
};

struct snatch_fzx_transform_data {
    std::uint8_t height{0};   // recommended baseline gap
    std::int8_t tracking{1};  // char spacing
    std::uint8_t lastchar{127};
    std::uint16_t glyph_count{0};
    const snatch_fzx_glyph_info* glyphs{nullptr};
};
